# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d22c8b77aecd08a6e13b376191ec2d4772d38ff0df1b7fe8733dcde6b70a50d908de9cba7311ccc86afacab3eb6ce543b11674067ea296efc230f4651905804f
  
  facebook_app_id: 1316317928411372
  facebook_app_secret: 900b904ffd8729b925d250fb4559a108

  twitter_app_id: 4FkwEK5U1AAJWqZnwp0mfG2il
  twitter_app_secret: VzP7jMg0Mv3AQfKXL1prqSaErJqwOo4ZBPPsXtu5cxJvTC60OE

test:
  secret_key_base: c28cee3ae1e11e83e41f2d7963c1457df19464fbd2139585ec6fb80356f3a8524c2b4d36c5a56d709b3750f123a1bfd0a5b6f9c84b35690a2af6caa3c5c170db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

  twitter_app_id: <%= ENV["TWITTER_APP_ID"] %>
  twitter_app_secret: <%= ENV["TWITTER_APP_SECRET"] %>
